import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import ts from 'typescript';
const urls=new Map();
async function moduleUrl(file){if(urls.has(file))return urls.get(file);let code=ts.transpileModule(await readFile(`src/features/incident-zero/defence/${file}.ts`,'utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2020}}).outputText;for(const dependency of [...code.matchAll(/from ['"]\.\/([^'"]+)['"]/g)])code=code.replace(dependency[0],`from ${JSON.stringify(await moduleUrl(dependency[1]))}`);const url=`data:text/javascript;base64,${Buffer.from(code).toString('base64')}`;urls.set(file,url);return url;}
async function load(file){return import(await moduleUrl(file));}

const gen=await load('generation'),sim=await load('simulation'),run=await load('run'),nav=await load('navigation');
test('1000 seeds × five levels: reproducible, reachable with physical clearance, safe spawns and exact budgets',()=>{let fallbacks=0;const fallbackSeeds=[];const signatures=new Set();for(let seed=0;seed<1000;seed++)for(let level=1;level<=5;level++){const f=gen.generateFloor(`trial-${seed}`,level),again=gen.generateFloor(`trial-${seed}`,level);assert.deepEqual(f,again,`seed ${seed} level ${level}`);assert.deepEqual(gen.validateFloor(f),[],`seed ${seed} level ${level}`);assert.ok(f.walls.every(w=>w.w>0&&w.h>0));assert.ok(f.spawns.length<=12);if(f.fallback){fallbacks++;fallbackSeeds.push([seed,level]);}signatures.add(JSON.stringify(f.walls));}console.log({generated:5000,fallbacks,uniqueLayouts:signatures.size,fallbackSeeds});assert.ok(signatures.size>500);});
test('bounded failed validation uses reachable authored fallback on every level',()=>{for(let l=1;l<=5;l++){let calls=0;const f=gen.generateFloor('failure',l,{validate:()=>{calls++;return ['forced'];}});assert.equal(calls,4);assert.ok(f.fallback);assert.deepEqual(gen.validateFloor(f),[]);}});
const result=(r,outcome='victory',hits=0)=>{const b=gen.levelBudgets[r.level-1];return {attemptId:r.attemptId,level:r.level,flood:b.flood,probe:b.probe,hits,integrity:outcome==='victory'?3-hits:0,weapon:'fan',score:b.flood*100+b.probe*150+(outcome==='victory'?500+(hits===0?250:0):0),outcome};};
test('five level commits, repair, advance and final bonus are idempotent across reload',()=>{let r=run.startRun(run.freshRun(),'regression');for(let l=1;l<=5;l++){assert.equal(r.level,l);const x=result(r,'victory',1);r=run.commitLevel(r,x);assert.equal(run.commitLevel(r,x),r);assert.deepEqual(run.parseRun(JSON.stringify(r)),r);if(l<5){r=run.continueRun(r);assert.equal(r.checkpoint.integrity,3);assert.equal(run.continueRun(r),r);}}assert.equal(r.status,'victory');assert.equal(r.completed,1);assert.equal(r.best,r.score);assert.equal(r.score,8800);});
test('active recovery rolls current combat back together, preserves committed floors and entry tool',()=>{let r=run.startRun(run.freshRun(),'checkpoint');r=run.continueRun(run.commitLevel(r,result(r,'victory',2)));r={...r,weapon:'pulse'};const recovered=run.recoverRun(run.parseRun(JSON.stringify(r)));assert.equal(recovered.status,'paused');assert.equal(recovered.level,2);assert.equal(recovered.checkpoint.integrity,2);assert.equal(recovered.weapon,'fan');assert.equal(recovered.score,r.score);assert.equal(recovered.levels.length,1);});
test('defeat ends run, does not alter completed best; same and new seed retries reset progress',()=>{let r=run.startRun({...run.freshRun(),best:9000,completed:2},'same');r=run.commitLevel(r,result(r,'defeat',3));assert.equal(r.best,9000);assert.equal(r.completed,2);assert.deepEqual(run.parseRun(JSON.stringify(r)),r);assert.equal(run.startRun(r,r.seed).seed,'same');assert.notEqual(run.startRun(r).seed,r.seed);assert.equal(run.startRun(r,r.seed).score,0);});
test('corrupt/old/unsupported checkpoints and unavailable storage remain safe',()=>{for(const raw of ['bad','{}','{"version":1}',JSON.stringify({...run.freshRun(),generatorVersion:99}),JSON.stringify({...run.freshRun(),checkpoint:{integrity:0,weapon:'pulse'}})])assert.deepEqual(run.parseRun(raw),run.freshRun());const storage=run.createRunStore({getItem(){throw Error();},setItem(){throw Error();}}),r=run.startRun(run.freshRun(),'memory');storage.save(r);assert.deepEqual(storage.load(),r);});
test('Fan beats Pulse at close grouped targets, Pulse reaches beyond Fan',()=>{function shoot(weapon,xs){const floor={...sim.arena,walls:[],entry:{x:100,y:270},spawns:xs.map(p=>({...p,kind:'flood'}))};const s=sim.newCombat(weapon,floor);s.status='playing';s.player.angle=0;sim.fire(s);for(let i=0;i<24;i++)sim.step(s,sim.emptyInput(),1/120);return xs.length*4-s.enemies.reduce((a,e)=>a+e.hp,0);}const cluster=[{x:155,y:270},{x:165,y:295},{x:165,y:245}];assert.ok(shoot('fan',cluster)>shoot('pulse',cluster));assert.ok(shoot('pulse',[{x:200,y:270}])>0);assert.equal(shoot('fan',[{x:400,y:270}]),0);});
test('navigation work bounded per displayed frame and routes remain physically valid',()=>{const f=gen.generateFloor('navigation-regression',5),s=sim.newCombat('pulse',f);s.status='playing';for(const e of s.enemies)e.active=true;for(let i=0;i<300;i++){const before=s.navigationSearches;sim.step(s,sim.emptyInput(),1/60);assert.ok(s.navigationSearches-before<=1);for(const e of s.enemies)assert.equal(sim.blocked(e,13,f),false);}assert.ok(s.navigationSearches>0);assert.ok(nav.searchPath(f,f.entry,f.terminal).length>0);});
test('representative floors retain terminal access when either parallel crossing is closed',()=>{for(let seed=0;seed<100;seed++)for(let l=1;l<=5;l++){const f=gen.generateFloor(`loop-${seed}`,l);for(const [y,h] of [[16,254],[278,246]]){const closed={...f,walls:[...f.walls,{x:f.fallback?590:593,y,w:f.fallback?24:14,h}]};assert.ok(nav.searchPath(closed,closed.entry,closed.terminal).length>0,`loop-${seed} / ${l} crossing ${y}`);}}});
test('fallback regression seeds stay valid, deterministic and bounded',()=>{for(const [seed,l] of [[133,2],[427,3],[457,3],[479,3],[699,1],[731,2],[836,2]]){const f=gen.generateFloor(`trial-${seed}`,l);assert.deepEqual(gen.validateFloor(f),[]);assert.deepEqual(f,gen.generateFloor(`trial-${seed}`,l));}});
test('generated entry grace prevents immediate attacks and wall-blocked shots persist',()=>{const f=gen.generateFloor('entry-grace',5),s=sim.newCombat('pulse',f);s.status='playing';for(let i=0;i<100;i++)sim.step(s,sim.emptyInput(),1/60);assert.equal(s.player.integrity,3);assert.ok(s.enemies.every(e=>!e.active&&e.warning===0));});
test('spawn-to-entry paths include physically clear initial and subsequent segments',()=>{for(let seed=0;seed<100;seed++)for(let l=1;l<=5;l++){const f=gen.generateFloor(`path-clearance-${seed}`,l);for(const e of f.spawns){let previous=e;const path=sim.findPath(e,f.entry,f);assert.ok(path.length);for(const point of path){assert.ok(sim.lineOfSight(previous,point,13,f),`path-clearance-${seed}/${l}: ${JSON.stringify(previous)} → ${JSON.stringify(point)}`);previous=point;}}}});
test('Pulse has better sustained precision damage at medium range where Fan wastes its spread',()=>{const targetRadius=17,range=170;const rate=w=>w.angles.filter(a=>Math.abs(Math.sin(a)*range)<targetRadius).length*w.damage/w.cooldown;assert.ok(rate(sim.weapons.pulse)>rate(sim.weapons.fan));assert.equal(sim.weapons.fan.angles.length,5);assert.equal(sim.weapons.pulse.angles.length,1);});
